"""Adicionar campos github_link, featured, category e updated_at na tabela Project

Revision ID: 8a787b2a0005
Revises: 
Create Date: 2025-05-08 18:39:12.398059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a787b2a0005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('category')
        batch_op.drop_column('featured')
        batch_op.drop_column('github_link')

    # ### end Alembic commands ###
